[project]
name = "xlabs-ai-guide"
version = "0.1.0"
description = "A technical learning guide that identifies knowledge gaps and recommends what to learn next."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minsearch>=0.2.0",
    "openai>=3.16.2",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
